### ISSUE TITLE
Lower the TargetFrameworkVersion

### ISSUE THREAD

**Issue by tlaguz** [alexeyzimarev/Autofac.Extras.ServiceStack#1]
I would like to use this library in project that targets '.NETFramework,Version=v4.5'.
I can't target higher framework version because I have to keep compatibility with mono.
Is there any chance of lowering TargetFrameworkVersion?

**Comment by alexeyzimarev** [comment]
Will do

**Comment by alexeyzimarev** [comment]
Framework lowered to 4.5 in v2.0.2
