### ISSUE TITLE
Why doesn't AutofacIocAdapter.TryResolve use scope?

### ISSUE THREAD

**Issue by tlaguz** [alexeyzimarev/Autofac.Extras.ServiceStack#2]

**Comment by alexeyzimarev** [comment]
I was checking v3.9.71 for Resolve vs TryResolve calls and found that dependencies for services where resolved with Resolve<T>. Have you got any issues because of this?

**Comment by tlaguz** [comment]
Thanks for response.

No I haven't got any issues related with this.
I was analysing your code and I just wanted to be sure that this is not a mistake :smile:

**Comment by alexeyzimarev** [comment]
I added the scope resolution also in TryResolve, v2.0.2
